// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Comments    string
	Ingredients string
	Recipes     string
	Tags        string
	Users       string
}{
	Comments:    "comments",
	Ingredients: "ingredients",
	Recipes:     "recipes",
	Tags:        "tags",
	Users:       "users",
}
