// Code generated by SQLBoiler 4.10.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Ingredients", testIngredients)
	t.Run("Recipes", testRecipes)
}

func TestDelete(t *testing.T) {
	t.Run("Ingredients", testIngredientsDelete)
	t.Run("Recipes", testRecipesDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Ingredients", testIngredientsQueryDeleteAll)
	t.Run("Recipes", testRecipesQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Ingredients", testIngredientsSliceDeleteAll)
	t.Run("Recipes", testRecipesSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Ingredients", testIngredientsExists)
	t.Run("Recipes", testRecipesExists)
}

func TestFind(t *testing.T) {
	t.Run("Ingredients", testIngredientsFind)
	t.Run("Recipes", testRecipesFind)
}

func TestBind(t *testing.T) {
	t.Run("Ingredients", testIngredientsBind)
	t.Run("Recipes", testRecipesBind)
}

func TestOne(t *testing.T) {
	t.Run("Ingredients", testIngredientsOne)
	t.Run("Recipes", testRecipesOne)
}

func TestAll(t *testing.T) {
	t.Run("Ingredients", testIngredientsAll)
	t.Run("Recipes", testRecipesAll)
}

func TestCount(t *testing.T) {
	t.Run("Ingredients", testIngredientsCount)
	t.Run("Recipes", testRecipesCount)
}

func TestHooks(t *testing.T) {
	t.Run("Ingredients", testIngredientsHooks)
	t.Run("Recipes", testRecipesHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Ingredients", testIngredientsInsert)
	t.Run("Ingredients", testIngredientsInsertWhitelist)
	t.Run("Recipes", testRecipesInsert)
	t.Run("Recipes", testRecipesInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("IngredientToRecipeUsingRecipeidRecipe", testIngredientToOneRecipeUsingRecipeidRecipe)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("RecipeToRecipeidIngredients", testRecipeToManyRecipeidIngredients)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("IngredientToRecipeUsingRecipeidIngredients", testIngredientToOneSetOpRecipeUsingRecipeidRecipe)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("IngredientToRecipeUsingRecipeidIngredients", testIngredientToOneRemoveOpRecipeUsingRecipeidRecipe)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("RecipeToRecipeidIngredients", testRecipeToManyAddOpRecipeidIngredients)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("RecipeToRecipeidIngredients", testRecipeToManySetOpRecipeidIngredients)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("RecipeToRecipeidIngredients", testRecipeToManyRemoveOpRecipeidIngredients)
}

func TestReload(t *testing.T) {
	t.Run("Ingredients", testIngredientsReload)
	t.Run("Recipes", testRecipesReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Ingredients", testIngredientsReloadAll)
	t.Run("Recipes", testRecipesReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Ingredients", testIngredientsSelect)
	t.Run("Recipes", testRecipesSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Ingredients", testIngredientsUpdate)
	t.Run("Recipes", testRecipesUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Ingredients", testIngredientsSliceUpdateAll)
	t.Run("Recipes", testRecipesSliceUpdateAll)
}
