// Code generated by SQLBoiler 4.10.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRecipes(t *testing.T) {
	t.Parallel()

	query := Recipes()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRecipesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Recipe{}
	if err = randomize.Struct(seed, o, recipeDBTypes, true, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Recipes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRecipesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Recipe{}
	if err = randomize.Struct(seed, o, recipeDBTypes, true, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Recipes().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Recipes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRecipesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Recipe{}
	if err = randomize.Struct(seed, o, recipeDBTypes, true, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RecipeSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Recipes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRecipesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Recipe{}
	if err = randomize.Struct(seed, o, recipeDBTypes, true, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RecipeExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Recipe exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RecipeExists to return true, but got false.")
	}
}

func testRecipesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Recipe{}
	if err = randomize.Struct(seed, o, recipeDBTypes, true, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	recipeFound, err := FindRecipe(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if recipeFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRecipesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Recipe{}
	if err = randomize.Struct(seed, o, recipeDBTypes, true, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Recipes().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testRecipesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Recipe{}
	if err = randomize.Struct(seed, o, recipeDBTypes, true, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Recipes().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRecipesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	recipeOne := &Recipe{}
	recipeTwo := &Recipe{}
	if err = randomize.Struct(seed, recipeOne, recipeDBTypes, false, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}
	if err = randomize.Struct(seed, recipeTwo, recipeDBTypes, false, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = recipeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = recipeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Recipes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRecipesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	recipeOne := &Recipe{}
	recipeTwo := &Recipe{}
	if err = randomize.Struct(seed, recipeOne, recipeDBTypes, false, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}
	if err = randomize.Struct(seed, recipeTwo, recipeDBTypes, false, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = recipeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = recipeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Recipes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func recipeBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Recipe) error {
	*o = Recipe{}
	return nil
}

func recipeAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Recipe) error {
	*o = Recipe{}
	return nil
}

func recipeAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Recipe) error {
	*o = Recipe{}
	return nil
}

func recipeBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Recipe) error {
	*o = Recipe{}
	return nil
}

func recipeAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Recipe) error {
	*o = Recipe{}
	return nil
}

func recipeBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Recipe) error {
	*o = Recipe{}
	return nil
}

func recipeAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Recipe) error {
	*o = Recipe{}
	return nil
}

func recipeBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Recipe) error {
	*o = Recipe{}
	return nil
}

func recipeAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Recipe) error {
	*o = Recipe{}
	return nil
}

func testRecipesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Recipe{}
	o := &Recipe{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, recipeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Recipe object: %s", err)
	}

	AddRecipeHook(boil.BeforeInsertHook, recipeBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	recipeBeforeInsertHooks = []RecipeHook{}

	AddRecipeHook(boil.AfterInsertHook, recipeAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	recipeAfterInsertHooks = []RecipeHook{}

	AddRecipeHook(boil.AfterSelectHook, recipeAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	recipeAfterSelectHooks = []RecipeHook{}

	AddRecipeHook(boil.BeforeUpdateHook, recipeBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	recipeBeforeUpdateHooks = []RecipeHook{}

	AddRecipeHook(boil.AfterUpdateHook, recipeAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	recipeAfterUpdateHooks = []RecipeHook{}

	AddRecipeHook(boil.BeforeDeleteHook, recipeBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	recipeBeforeDeleteHooks = []RecipeHook{}

	AddRecipeHook(boil.AfterDeleteHook, recipeAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	recipeAfterDeleteHooks = []RecipeHook{}

	AddRecipeHook(boil.BeforeUpsertHook, recipeBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	recipeBeforeUpsertHooks = []RecipeHook{}

	AddRecipeHook(boil.AfterUpsertHook, recipeAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	recipeAfterUpsertHooks = []RecipeHook{}
}

func testRecipesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Recipe{}
	if err = randomize.Struct(seed, o, recipeDBTypes, true, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Recipes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRecipesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Recipe{}
	if err = randomize.Struct(seed, o, recipeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(recipeColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Recipes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRecipeToManyRecipeidIngredients(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Recipe
	var b, c Ingredient

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, recipeDBTypes, true, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, ingredientDBTypes, false, ingredientColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, ingredientDBTypes, false, ingredientColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.Recipeid, a.ID)
	queries.Assign(&c.Recipeid, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.RecipeidIngredients().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.Recipeid, b.Recipeid) {
			bFound = true
		}
		if queries.Equal(v.Recipeid, c.Recipeid) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := RecipeSlice{&a}
	if err = a.L.LoadRecipeidIngredients(ctx, tx, false, (*[]*Recipe)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.RecipeidIngredients); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.RecipeidIngredients = nil
	if err = a.L.LoadRecipeidIngredients(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.RecipeidIngredients); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testRecipeToManyRecipeidTags(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Recipe
	var b, c Tag

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, recipeDBTypes, true, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, tagDBTypes, false, tagColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, tagDBTypes, false, tagColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.Recipeid, a.ID)
	queries.Assign(&c.Recipeid, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.RecipeidTags().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.Recipeid, b.Recipeid) {
			bFound = true
		}
		if queries.Equal(v.Recipeid, c.Recipeid) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := RecipeSlice{&a}
	if err = a.L.LoadRecipeidTags(ctx, tx, false, (*[]*Recipe)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.RecipeidTags); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.RecipeidTags = nil
	if err = a.L.LoadRecipeidTags(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.RecipeidTags); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testRecipeToManyAddOpRecipeidIngredients(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Recipe
	var b, c, d, e Ingredient

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, recipeDBTypes, false, strmangle.SetComplement(recipePrimaryKeyColumns, recipeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Ingredient{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, ingredientDBTypes, false, strmangle.SetComplement(ingredientPrimaryKeyColumns, ingredientColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Ingredient{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddRecipeidIngredients(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.Recipeid) {
			t.Error("foreign key was wrong value", a.ID, first.Recipeid)
		}
		if !queries.Equal(a.ID, second.Recipeid) {
			t.Error("foreign key was wrong value", a.ID, second.Recipeid)
		}

		if first.R.RecipeidRecipe != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.RecipeidRecipe != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.RecipeidIngredients[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.RecipeidIngredients[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.RecipeidIngredients().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testRecipeToManySetOpRecipeidIngredients(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Recipe
	var b, c, d, e Ingredient

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, recipeDBTypes, false, strmangle.SetComplement(recipePrimaryKeyColumns, recipeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Ingredient{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, ingredientDBTypes, false, strmangle.SetComplement(ingredientPrimaryKeyColumns, ingredientColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetRecipeidIngredients(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.RecipeidIngredients().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetRecipeidIngredients(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.RecipeidIngredients().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.Recipeid) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.Recipeid) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.Recipeid) {
		t.Error("foreign key was wrong value", a.ID, d.Recipeid)
	}
	if !queries.Equal(a.ID, e.Recipeid) {
		t.Error("foreign key was wrong value", a.ID, e.Recipeid)
	}

	if b.R.RecipeidRecipe != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.RecipeidRecipe != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.RecipeidRecipe != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.RecipeidRecipe != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.RecipeidIngredients[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.RecipeidIngredients[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testRecipeToManyRemoveOpRecipeidIngredients(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Recipe
	var b, c, d, e Ingredient

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, recipeDBTypes, false, strmangle.SetComplement(recipePrimaryKeyColumns, recipeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Ingredient{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, ingredientDBTypes, false, strmangle.SetComplement(ingredientPrimaryKeyColumns, ingredientColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddRecipeidIngredients(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.RecipeidIngredients().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveRecipeidIngredients(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.RecipeidIngredients().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.Recipeid) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.Recipeid) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.RecipeidRecipe != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.RecipeidRecipe != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.RecipeidRecipe != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.RecipeidRecipe != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.RecipeidIngredients) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.RecipeidIngredients[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.RecipeidIngredients[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testRecipeToManyAddOpRecipeidTags(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Recipe
	var b, c, d, e Tag

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, recipeDBTypes, false, strmangle.SetComplement(recipePrimaryKeyColumns, recipeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Tag{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, tagDBTypes, false, strmangle.SetComplement(tagPrimaryKeyColumns, tagColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Tag{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddRecipeidTags(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.Recipeid) {
			t.Error("foreign key was wrong value", a.ID, first.Recipeid)
		}
		if !queries.Equal(a.ID, second.Recipeid) {
			t.Error("foreign key was wrong value", a.ID, second.Recipeid)
		}

		if first.R.RecipeidRecipe != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.RecipeidRecipe != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.RecipeidTags[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.RecipeidTags[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.RecipeidTags().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testRecipeToManySetOpRecipeidTags(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Recipe
	var b, c, d, e Tag

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, recipeDBTypes, false, strmangle.SetComplement(recipePrimaryKeyColumns, recipeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Tag{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, tagDBTypes, false, strmangle.SetComplement(tagPrimaryKeyColumns, tagColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetRecipeidTags(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.RecipeidTags().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetRecipeidTags(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.RecipeidTags().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.Recipeid) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.Recipeid) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.Recipeid) {
		t.Error("foreign key was wrong value", a.ID, d.Recipeid)
	}
	if !queries.Equal(a.ID, e.Recipeid) {
		t.Error("foreign key was wrong value", a.ID, e.Recipeid)
	}

	if b.R.RecipeidRecipe != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.RecipeidRecipe != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.RecipeidRecipe != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.RecipeidRecipe != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.RecipeidTags[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.RecipeidTags[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testRecipeToManyRemoveOpRecipeidTags(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Recipe
	var b, c, d, e Tag

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, recipeDBTypes, false, strmangle.SetComplement(recipePrimaryKeyColumns, recipeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Tag{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, tagDBTypes, false, strmangle.SetComplement(tagPrimaryKeyColumns, tagColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddRecipeidTags(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.RecipeidTags().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveRecipeidTags(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.RecipeidTags().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.Recipeid) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.Recipeid) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.RecipeidRecipe != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.RecipeidRecipe != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.RecipeidRecipe != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.RecipeidRecipe != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.RecipeidTags) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.RecipeidTags[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.RecipeidTags[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testRecipesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Recipe{}
	if err = randomize.Struct(seed, o, recipeDBTypes, true, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRecipesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Recipe{}
	if err = randomize.Struct(seed, o, recipeDBTypes, true, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RecipeSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRecipesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Recipe{}
	if err = randomize.Struct(seed, o, recipeDBTypes, true, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Recipes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	recipeDBTypes = map[string]string{`ID`: `INTEGER`, `URL`: `TEXT`, `Title`: `TEXT`, `Instructions`: `TEXT`, `Author`: `TEXT`, `TotalTime`: `INT`, `Yields`: `TEXT`, `ServingSize`: `TEXT`, `Calories`: `TEXT`, `Image`: `BLOB`, `Path`: `TEXT`}
	_             = bytes.MinRead
)

func testRecipesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(recipePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(recipeAllColumns) == len(recipePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Recipe{}
	if err = randomize.Struct(seed, o, recipeDBTypes, true, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Recipes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, recipeDBTypes, true, recipePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRecipesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(recipeAllColumns) == len(recipePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Recipe{}
	if err = randomize.Struct(seed, o, recipeDBTypes, true, recipeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Recipes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, recipeDBTypes, true, recipePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(recipeAllColumns, recipePrimaryKeyColumns) {
		fields = recipeAllColumns
	} else {
		fields = strmangle.SetComplement(
			recipeAllColumns,
			recipePrimaryKeyColumns,
		)
		fields = strmangle.SetComplement(fields, recipeGeneratedColumns)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RecipeSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testRecipesUpsert(t *testing.T) {
	t.Parallel()
	if len(recipeAllColumns) == len(recipePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Recipe{}
	if err = randomize.Struct(seed, &o, recipeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Recipe: %s", err)
	}

	count, err := Recipes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, recipeDBTypes, false, recipePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Recipe struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Recipe: %s", err)
	}

	count, err = Recipes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
