// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Comments", testCommentsUpsert)

	t.Run("Ingredients", testIngredientsUpsert)

	t.Run("Recipes", testRecipesUpsert)

	t.Run("Tags", testTagsUpsert)

	t.Run("Users", testUsersUpsert)
}
